DROP TABLE IF EXISTS measurements;
DROP TABLE IF EXISTS sensor;

CREATE TABLE sensor (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(30) NOT NULL UNIQUE,
	CONSTRAINT NAME_MIN_SIZE CHECK (LENGTH(name)>0)
);
CREATE TABLE measurements (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	temperature decimal CHECK(temperature>(-50)AND temperature<50),
	raining boolean,
	time_of_measurement timestamp,
	sensor_id int REFERENCES sensor(id) ON UPDATE CASCADE ON DELETE CASCADE
)